IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SIM_FARM_BTN')
    CREATE DATABASE SIM_FARM_BTNN;
GO

USE SIM_FARM_BTNN;
GO


CREATE TABLE CUSTOMER
(
  id_customer INT NOT NULL,
  nama_customer VARCHAR(100) NOT NULL,
  jenis_customer VARCHAR(100) NOT NULL,
  PRIMARY KEY (id_customer)
);