IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SIM_FARM_BTN')
    CREATE DATABASE SIM_FARM_BTNN;
GO

USE SIM_FARM_BTNN;
GO


CREATE TABLE GUDANG
(
  id_gudang INT NOT NULL,
  nama_gudang VARCHAR(100) NOT NULL,
  lokasi VARCHAR(200) NOT NULL,
  PRIMARY KEY (id_gudang)
);