IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SIM_FARM_BT')
    CREATE DATABASE SIM_FARM_BTN;
GO

USE SIM_FARM_BTN;
GO


CREATE TABLE PAKAN
(
  id_pakan INT NOT NULL,
  nama_pakan VARCHAR(100) NOT NULL,
  stok INT NOT NULL,
  id_gudang INT NOT NULL,
  PRIMARY KEY (id_pakan),
  FOREIGN KEY (id_gudang) REFERENCES GUDANG(id_gudang)
);