IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SIM_FARM_BT')
    CREATE DATABASE SIM_FARM_BTN;
GO

USE SIM_FARM_BTN;
GO


CREATE TABLE SUPPLIER
(
  id_supplier INT NOT NULL,
  nama_supplier VARCHAR(100) NOT NULL,
  kontak VARCHAR(20) NOT NULL,
  PRIMARY KEY (id_supplier)
);