CREATE TABLE DOKTERHEWAN
(
  KaryawanID INT NOT NULL,
  NoSIP VARCHAR(50) NOT NULL,
  Spesialisasi VARCHAR(100) NOT NULL,
  StatusMitra VARCHAR(30) NOT NULL,
  BiayaKunjungan INT NOT NULL,
  PRIMARY KEY (KaryawanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID)
);