CREATE TABLE KARYAWAN
(
  KaryawanID INT NOT NULL,
  Nama VARCHAR(100) NOT NULL,
  NIK VARCHAR(20) NOT NULL,
  TanggalLahir DATE NOT NULL,
  Alamat VARCHAR(200) NOT NULL,
  Telepon VARCHAR(20) NOT NULL,
  JenisKelamin CHAR(1) NOT NULL,
  TanggalMasuk DATE NOT NULL,
  TipeKaryawan VARCHAR(50) NOT NULL,
  FarmID INT NOT NULL,
  PRIMARY KEY (KaryawanID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID)
);