CREATE TABLE KEMATIANAYAM
(
  KematianID INT NOT NULL,
  TanggalKematian DATE NOT NULL,
  JumlahMati INT NOT NULL,
  Penyebab VARCHAR(100) NOT NULL,
  BatchID INT NOT NULL,
  KaryawanID INT NOT NULL,
  PRIMARY KEY (KematianID),
  FOREIGN KEY (BatchID) REFERENCES BATCH(BatchID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID)
);