CREATE TABLE PANENTELUR
(
  PanenID INT NOT NULL,
  TanggalPanen DATE NOT NULL,
  KaryawanID INT NOT NULL,
  BatchID INT NOT NULL,
  PRIMARY KEY (PanenID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID),
  FOREIGN KEY (BatchID) REFERENCES BATCH(BatchID)
);