CREATE TABLE STOKGUDANGPAKAN
(
  StokPakanID INT NOT NULL,
  JumlahStokKg INT NOT NULL,
  TanggalUpdate DATE NOT NULL,
  TanggalKadaluarsa DATE,
  FarmID INT NOT NULL,
  PakanID INT NOT NULL,
  PRIMARY KEY (StokPakanID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID),
  FOREIGN KEY (PakanID) REFERENCES PAKAN(PakanID)
);