CREATE TABLE DETAILPANEN
(
  DetailPanenID INT NOT NULL,
  GradeTelur VARCHAR(50) NOT NULL, 
  JumlahButir INT NOT NULL,
  BeratKg NUMERIC(7,2) NOT NULL,
  PanenID INT NOT NULL,
  PRIMARY KEY (DetailPanenID),
  FOREIGN KEY (PanenID) REFERENCES PANENTELUR(PanenID) ON DELETE CASCADE
);