CREATE TABLE PAKAN
(
  PakanID INT NOT NULL,
  NamaPakan VARCHAR(100) NOT NULL,
  Merek VARCHAR(100) NOT NULL,
  JenisPakan VARCHAR(50) NOT NULL,
  HargaPerKg INT NOT NULL,
  PRIMARY KEY (PakanID)
);

