CREATE TABLE PEKERJAHARIAN
(
  KaryawanID INT NOT NULL,
  UpahPerHari INT NOT NULL,
  JadwalShift VARCHAR(50) NOT NULL,
  PRIMARY KEY (KaryawanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID)
);