CREATE TABLE PEMBERIANPAKAN
(
  FeedingID INT NOT NULL,
  TanggalFeeding DATE NOT NULL,
  Sesi VARCHAR(20) NOT NULL,
  JumlahKg INT NOT NULL,
  BatchID INT NOT NULL,
  PakanID INT NOT NULL,
  KaryawanID INT NOT NULL,
  PRIMARY KEY (FeedingID),
  FOREIGN KEY (BatchID) REFERENCES BATCH(BatchID),
  FOREIGN KEY (PakanID) REFERENCES PAKAN(PakanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KARYAWAN)
);