CREATE TABLE PEMBELIANPAKAN
(
  PembelianID INT NOT NULL,
  TanggalBeli DATE NOT NULL,
  JumlahKg INT NOT NULL,
  HargaTotal INT NOT NULL,
  SupplierID INT NOT NULL,
  PakanID INT NOT NULL,
  FarmID INT NOT NULL, 
  PRIMARY KEY (PembelianID),
  FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID),
  FOREIGN KEY (PakanID) REFERENCES PAKAN(PakanID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID)
);