CREATE TABLE PENJUALANTELUR
(
  PenjualanID INT NOT NULL,
  TanggalJual DATE NOT NULL,
  TotalBerat NUMERIC(9,2) NOT NULL,
  TotalHarga INT NOT NULL,
  KaryawanID INT NOT NULL,
  CustomerID INT NOT NULL,
  PRIMARY KEY (PenjualanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);