USE master;
GO

IF EXISTS (SELECT name FROM sys.databases WHERE name = 'SIM_FARM_BTN')
BEGIN
    ALTER DATABASE SIM_FARM_BTN SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE SIM_FARM_BTN;
END
GO

CREATE DATABASE SIM_FARM_BTN;
GO
USE SIM_FARM_BTN;
GO

CREATE TABLE BATCH
(
  BatchID INT NOT NULL,
  KodeAyam VARCHAR(50) NOT NULL,
  JenisAyam VARCHAR(100) NOT NULL,
  TanggalMasuk DATE NOT NULL,
  JumlahAyamAwal INT NOT NULL,
  PopulasiSekarang INT NOT NULL,
  StatusBatch VARCHAR(30) NOT NULL,
  KandangID INT NOT NULL,
  PRIMARY KEY (BatchID),
  FOREIGN KEY (KandangID) REFERENCES KANDANG(KandangID)
);CREATE TABLE CUSTOMER
(
  CustomerID INT NOT NULL,
  NamaCustomer VARCHAR(100) NOT NULL,
  TipeCustomer VARCHAR(50) NOT NULL,
  Alamat VARCHAR(200) NOT NULL,
  Telepon VARCHAR(20) NOT NULL,
  PRIMARY KEY (CustomerID)
);CREATE TABLE DETAILPANEN
(
  DetailPanenID INT NOT NULL,
  GradeTelur VARCHAR(50) NOT NULL, 
  JumlahButir INT NOT NULL,
  BeratKg NUMERIC(7,2) NOT NULL,
  PanenID INT NOT NULL,
  PRIMARY KEY (DetailPanenID),
  FOREIGN KEY (PanenID) REFERENCES PANENTELUR(PanenID) ON DELETE CASCADE
);CREATE TABLE DETAILPENJUALAN
(
  DetailID INT NOT NULL,
  GradeTelur VARCHAR(50) NOT NULL,
  JumlahButir INT NOT NULL,
  BeratKg NUMERIC(7,2) NOT NULL,
  HargaPerKg INT NOT NULL,
  BatchID INT NOT NULL, -- FK ke Batch sesuai dengan erdplus (11).jpg kalian
  PenjualanID INT NOT NULL,
  PRIMARY KEY (DetailID),
  FOREIGN KEY (BatchID) REFERENCES BATCH(BatchID),
  FOREIGN KEY (PenjualanID) REFERENCES PENJUALANTELUR(PenjualanID) ON DELETE CASCADE
);
CREATE TABLE DOKTERHEWAN
(
  KaryawanID INT NOT NULL,
  NoSIP VARCHAR(50) NOT NULL,
  Spesialisasi VARCHAR(100) NOT NULL,
  StatusMitra VARCHAR(30) NOT NULL,
  BiayaKunjungan INT NOT NULL,
  PRIMARY KEY (KaryawanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID)
);CREATE TABLE FARM
(
  FarmID INT NOT NULL,
  NamaFarm VARCHAR(100) NOT NULL,
  Alamat VARCHAR(200) NOT NULL,
  TeleponFarm VARCHAR(20) NOT NULL,
  PRIMARY KEY (FarmID)
);

CREATE TABLE KANDANG
(
  KandangID INT NOT NULL,
  NamaKandang VARCHAR(100) NOT NULL,
  KapasitasMaksimal INT NOT NULL,
  StatusKandang VARCHAR(30) NOT NULL,
  TipeKandang VARCHAR(50) NOT NULL,
  FarmID INT NOT NULL,
  PRIMARY KEY (KandangID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID)
);CREATE TABLE KANDANGTANGGUNGJAWAB 
(
  KaryawanID INT NOT NULL,
  KandangID INT NOT NULL,
  TanggalDitugaskan DATE DEFAULT GETDATE(),
  
  -- Composite Primary Key
  PRIMARY KEY (KaryawanID, KandangID),
  
  -- Foreign Key mengarah ke Subtype Mandor dan Kandang dengan Cascade Action
  FOREIGN KEY (KaryawanID) REFERENCES MANDORKANDANG(KaryawanID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (KandangID) REFERENCES KANDANG(KandangID) ON DELETE CASCADE ON UPDATE CASCADE
);CREATE TABLE KARYAWAN
(
  KaryawanID INT NOT NULL,
  Nama VARCHAR(100) NOT NULL,
  NIK VARCHAR(20) NOT NULL,
  TanggalLahir DATE NOT NULL,
  Alamat VARCHAR(200) NOT NULL,
  Telepon VARCHAR(20) NOT NULL,
  JenisKelamin CHAR(1) NOT NULL,
  TanggalMasuk DATE NOT NULL,
  TipeKaryawan VARCHAR(50) NOT NULL,
  FarmID INT NOT NULL,
  PRIMARY KEY (KaryawanID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID)
);CREATE TABLE MANAJERFARM
(
  KaryawanID INT NOT NULL,
  GajiPokok INT NOT NULL,
  TanggalPengangkatan DATE NOT NULL,
  PRIMARY KEY (KaryawanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID)
);CREATE TABLE MANDORKANDANG
(
  KaryawanID INT NOT NULL,
  GajiPokok INT NOT NULL,
  PRIMARY KEY (KaryawanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID)
);CREATE TABLE OBAT
(
  ObatID INT NOT NULL,
  NamaObat VARCHAR(100) NOT NULL,
  JenisObat VARCHAR(50) NOT NULL,
  Satuan VARCHAR(20) NOT NULL,
  PRIMARY KEY (ObatID)
);

CREATE TABLE PAKAN
(
  PakanID INT NOT NULL,
  NamaPakan VARCHAR(100) NOT NULL,
  Merek VARCHAR(100) NOT NULL,
  JenisPakan VARCHAR(50) NOT NULL,
  HargaPerKg INT NOT NULL,
  PRIMARY KEY (PakanID)
);

CREATE TABLE PANENTELUR
(
  PanenID INT NOT NULL,
  TanggalPanen DATE NOT NULL,
  KaryawanID INT NOT NULL,
  BatchID INT NOT NULL,
  PRIMARY KEY (PanenID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID),
  FOREIGN KEY (BatchID) REFERENCES BATCH(BatchID)
);CREATE TABLE PEKERJAHARIAN
(
  KaryawanID INT NOT NULL,
  UpahPerHari INT NOT NULL,
  JadwalShift VARCHAR(50) NOT NULL,
  PRIMARY KEY (KaryawanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID)
);CREATE TABLE PEMBELIANPAKAN
(
  PembelianID INT NOT NULL,
  TanggalBeli DATE NOT NULL,
  JumlahKg INT NOT NULL,
  HargaTotal INT NOT NULL,
  SupplierID INT NOT NULL,
  PakanID INT NOT NULL,
  FarmID INT NOT NULL, 
  PRIMARY KEY (PembelianID),
  FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID),
  FOREIGN KEY (PakanID) REFERENCES PAKAN(PakanID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID)
);CREATE TABLE PENJUALANTELUR
(
  PenjualanID INT NOT NULL,
  TanggalJual DATE NOT NULL,
  TotalBerat NUMERIC(9,2) NOT NULL,
  TotalHarga INT NOT NULL,
  KaryawanID INT NOT NULL,
  CustomerID INT NOT NULL,
  PRIMARY KEY (PenjualanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);CREATE TABLE STOKGUDANGOBAT
(
  StokObatID INT NOT NULL,
  JumlahStok INT NOT NULL,
  TanggalUpdate DATE NOT NULL,
  ObatID INT NOT NULL,
  FarmID INT NOT NULL,
  PRIMARY KEY (StokObatID),
  FOREIGN KEY (ObatID) REFERENCES OBAT(ObatID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID)
);CREATE TABLE STOKGUDANGPAKAN
(
  StokPakanID INT NOT NULL,
  JumlahStokKg INT NOT NULL,
  TanggalUpdate DATE NOT NULL,
  TanggalKadaluarsa DATE,
  FarmID INT NOT NULL,
  PakanID INT NOT NULL,
  PRIMARY KEY (StokPakanID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID),
  FOREIGN KEY (PakanID) REFERENCES PAKAN(PakanID)
);CREATE TABLE SUPPLIER
(
  SupplierID INT NOT NULL,
  NamaSupplier VARCHAR(100) NOT NULL,
  Alamat VARCHAR(200) NOT NULL,
  Telepon VARCHAR(20) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  PRIMARY KEY (SupplierID)
);

CREATE TABLE KEMATIANAYAM
(
  KematianID INT NOT NULL,
  TanggalKematian DATE NOT NULL,
  JumlahMati INT NOT NULL,
  Penyebab VARCHAR(100) NOT NULL,
  BatchID INT NOT NULL,
  KaryawanID INT NOT NULL,
  PRIMARY KEY (KematianID),
  FOREIGN KEY (BatchID) REFERENCES BATCH(BatchID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID)
);CREATE TABLE PEMBELIANOBAT
(
  PembelianObatID INT NOT NULL,
  TanggalBeli DATE NOT NULL,
  JumlahStok INT NOT NULL,     
  HargaTotal INT NOT NULL,
  FarmID INT NOT NULL,
  SupplierID INT NOT NULL,
  PRIMARY KEY (PembelianObatID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID),
  FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID)
);CREATE TABLE PEMBERIANPAKAN
(
  FeedingID INT NOT NULL,
  TanggalFeeding DATE NOT NULL,
  Sesi VARCHAR(20) NOT NULL,
  JumlahKg INT NOT NULL,
  BatchID INT NOT NULL,
  PakanID INT NOT NULL,
  KaryawanID INT NOT NULL,
  PRIMARY KEY (FeedingID),
  FOREIGN KEY (BatchID) REFERENCES BATCH(BatchID),
  FOREIGN KEY (PakanID) REFERENCES PAKAN(PakanID),
  FOREIGN KEY (KaryawanID) REFERENCES KARYAWAN(KaryawanID)
);CREATE TABLE TINDAKANMEDIS
(
  MedisID INT NOT NULL,
  TanggalTindakan DATE NOT NULL,
  JenisTindakan VARCHAR(50) NOT NULL,
  DosisAktual INT NOT NULL,
  Keterangan VARCHAR(200),
  BatchID INT NOT NULL,
  ObatID INT NOT NULL,
  DokterID INT NOT NULL,
  PRIMARY KEY (MedisID),
  FOREIGN KEY (BatchID) REFERENCES BATCH(BatchID),
  FOREIGN KEY (ObatID) REFERENCES OBAT(ObatID),
  FOREIGN KEY (DokterID) REFERENCES KARYAWAN(KaryawanID)
);