CREATE TABLE STOKGUDANGOBAT
(
  StokObatID INT NOT NULL,
  JumlahStok INT NOT NULL,
  TanggalUpdate DATE NOT NULL,
  ObatID INT NOT NULL,
  FarmID INT NOT NULL,
  PRIMARY KEY (StokObatID),
  FOREIGN KEY (ObatID) REFERENCES OBAT(ObatID),
  FOREIGN KEY (FarmID) REFERENCES FARM(FarmID)
);