CREATE TABLE SUPPLIER
(
  SupplierID INT NOT NULL,
  NamaSupplier VARCHAR(100) NOT NULL,
  Alamat VARCHAR(200) NOT NULL,
  Telepon VARCHAR(20) NOT NULL,
  Email VARCHAR(100) NOT NULL,
  PRIMARY KEY (SupplierID)
);

