CREATE TABLE TINDAKANMEDIS
(
  MedisID INT NOT NULL,
  TanggalTindakan DATE NOT NULL,
  JenisTindakan VARCHAR(50) NOT NULL,
  DosisAktual INT NOT NULL,
  Keterangan VARCHAR(200),
  BatchID INT NOT NULL,
  ObatID INT NOT NULL,
  DokterID INT NOT NULL,
  PRIMARY KEY (MedisID),
  FOREIGN KEY (BatchID) REFERENCES BATCH(BatchID),
  FOREIGN KEY (ObatID) REFERENCES OBAT(ObatID),
  FOREIGN KEY (DokterID) REFERENCES KARYAWAN(KARYAWAN)
);