IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SIM_FARM_BTN')
    CREATE DATABASE SIM_FARM_BTN;
GO

USE SIM_FARM_BTN;
GO


CREATE TABLE FARM
(
  id_farm INT NOT NULL,
  nama_farm VARCHAR(100) NOT NULL,
  lokasi VARCHAR(100) NOT NULL,
  PRIMARY KEY (id_farm)
);