IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'SIM_FARM_BTN')
    CREATE DATABASE SIM_FARM_BTN;
GO

USE SIM_FARM_BTN;
GO


CREATE TABLE KARYAWAN
(
  id_karyawan INT NOT NULL,
  nama VARCHAR(100) NOT NULL,
  peran VARCHAR(100) NOT NULL,
  id_farm INT NOT NULL,
  PRIMARY KEY (id_karyawan),
  FOREIGN KEY (id_farm) REFERENCES FARM(id_farm)
);